# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'cloud'
    sourceRepo: 'npm'
    workingFolder: 'npm-example'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryNpm@2
  inputs:
    command: 'pack and publish'
    artifactoryService: 'cloud'
    targetRepo: 'npm'
    workingFolder: 'npm-example'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'cloud'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'cloud'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
